<?php
/**
 * ComputerResourceHardwareAnyOfPeripherals
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  WhatPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhatPulse API
 *
 * Public API for WhatPulse user data access. This API allows authenticated users to access their own data and public data from other users, depending on privacy settings.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace WhatPulse\Model;

use \ArrayAccess;
use \WhatPulse\ObjectSerializer;

/**
 * ComputerResourceHardwareAnyOfPeripherals Class Doc Comment
 *
 * @category Class
 * @package  WhatPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ComputerResourceHardwareAnyOfPeripherals implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ComputerResource_hardware_anyOf_peripherals';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'monitors' => 'mixed[]',
        'keyboard' => 'mixed[]',
        'mouse' => 'mixed[]',
        'trackpad' => 'mixed[]',
        'controllers' => 'mixed[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'monitors' => null,
        'keyboard' => null,
        'mouse' => null,
        'trackpad' => null,
        'controllers' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'monitors' => false,
        'keyboard' => false,
        'mouse' => false,
        'trackpad' => false,
        'controllers' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'monitors' => 'monitors',
        'keyboard' => 'keyboard',
        'mouse' => 'mouse',
        'trackpad' => 'trackpad',
        'controllers' => 'controllers'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'monitors' => 'setMonitors',
        'keyboard' => 'setKeyboard',
        'mouse' => 'setMouse',
        'trackpad' => 'setTrackpad',
        'controllers' => 'setControllers'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'monitors' => 'getMonitors',
        'keyboard' => 'getKeyboard',
        'mouse' => 'getMouse',
        'trackpad' => 'getTrackpad',
        'controllers' => 'getControllers'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('monitors', $data ?? [], null);
        $this->setIfExists('keyboard', $data ?? [], null);
        $this->setIfExists('mouse', $data ?? [], null);
        $this->setIfExists('trackpad', $data ?? [], null);
        $this->setIfExists('controllers', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['monitors'] === null) {
            $invalidProperties[] = "'monitors' can't be null";
        }
        if ($this->container['keyboard'] === null) {
            $invalidProperties[] = "'keyboard' can't be null";
        }
        if ($this->container['mouse'] === null) {
            $invalidProperties[] = "'mouse' can't be null";
        }
        if ($this->container['trackpad'] === null) {
            $invalidProperties[] = "'trackpad' can't be null";
        }
        if ($this->container['controllers'] === null) {
            $invalidProperties[] = "'controllers' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets monitors
     *
     * @return mixed[]
     */
    public function getMonitors()
    {
        return $this->container['monitors'];
    }

    /**
     * Sets monitors
     *
     * @param mixed[] $monitors The list of monitors connected to the computer.
     *
     * @return self
     */
    public function setMonitors($monitors)
    {
        if (is_null($monitors)) {
            throw new \InvalidArgumentException('non-nullable monitors cannot be null');
        }
        $this->container['monitors'] = $monitors;

        return $this;
    }

    /**
     * Gets keyboard
     *
     * @return mixed[]
     */
    public function getKeyboard()
    {
        return $this->container['keyboard'];
    }

    /**
     * Sets keyboard
     *
     * @param mixed[] $keyboard The list of keyboards connected to the computer.
     *
     * @return self
     */
    public function setKeyboard($keyboard)
    {
        if (is_null($keyboard)) {
            throw new \InvalidArgumentException('non-nullable keyboard cannot be null');
        }
        $this->container['keyboard'] = $keyboard;

        return $this;
    }

    /**
     * Gets mouse
     *
     * @return mixed[]
     */
    public function getMouse()
    {
        return $this->container['mouse'];
    }

    /**
     * Sets mouse
     *
     * @param mixed[] $mouse The list of mice connected to the computer.
     *
     * @return self
     */
    public function setMouse($mouse)
    {
        if (is_null($mouse)) {
            throw new \InvalidArgumentException('non-nullable mouse cannot be null');
        }
        $this->container['mouse'] = $mouse;

        return $this;
    }

    /**
     * Gets trackpad
     *
     * @return mixed[]
     */
    public function getTrackpad()
    {
        return $this->container['trackpad'];
    }

    /**
     * Sets trackpad
     *
     * @param mixed[] $trackpad The trackpad information, if available.
     *
     * @return self
     */
    public function setTrackpad($trackpad)
    {
        if (is_null($trackpad)) {
            throw new \InvalidArgumentException('non-nullable trackpad cannot be null');
        }
        $this->container['trackpad'] = $trackpad;

        return $this;
    }

    /**
     * Gets controllers
     *
     * @return mixed[]
     */
    public function getControllers()
    {
        return $this->container['controllers'];
    }

    /**
     * Sets controllers
     *
     * @param mixed[] $controllers The list of game controller devices connected to the computer.
     *
     * @return self
     */
    public function setControllers($controllers)
    {
        if (is_null($controllers)) {
            throw new \InvalidArgumentException('non-nullable controllers cannot be null');
        }
        $this->container['controllers'] = $controllers;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


